apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: {{ .Values.appName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
    template:
      metadata:
        labels: 
          app: {{ .Values.appName }}
      spec:
        containers:
          -name: flask-container
          image: chas3bg/flask-hello
          ports:
            containerPorts: 5000