apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-101
  template:
    metadata:
      labels: 
        app: flask-101
    spec:
      containers:
        - name: flask-container
          image: "chas3bg/flask-hello:1.1"
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5